use_frameworks!

platform :ios, '8.0'

target 'HIBaseToolKit_Example' do
  pod 'HIBaseToolKit', :path => '../'

  target 'HIBaseToolKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
